from __future__ import annotations

import json
from datetime import datetime
from pathlib import Path
from typing import Literal

from pydantic import BaseModel, Field, ValidationError, field_validator, model_validator

from .automation import automation_for

# The four verdict states every check returns. Shared so each check module's _make()
# helper can type its `status` parameter without a per-call type: ignore.
CheckStatus = Literal["PASS", "FAIL", "NA", "MANUAL_REVIEW"]


class ConfigError(Exception):
    """Configuration problem with a user-facing, plain-language message.

    Raised by Config.load() instead of letting json/pydantic stack traces reach
    non-developer users. validator.py prints str(exc) without a traceback.
    """


# Config keys whose Excel cell holds a comma-separated list.
_LIST_KEYS = {
    "vut_entity_names", "encap_actor_names", "sov_entity_names",
    "static_target_name_patterns", "stationary_target_name_patterns",
    "required_file_extensions", "required_standalone_files",
    "optional_standalone_files",
    "extra_scenario_prefixes",
    "allowed_programs", "target_type_tokens", "required_associated_roles",
    "allowed_impact_overlaps",
}


def _read_excel_config(path: Path) -> dict:
    """Read config.xlsx (generated by tools/make_config_xlsx.py) into the same raw
    dict shape that json.loads(config.json) produces. Sheets:
      Protocol Constants / Site Settings : key | value | description rows
      Scenarios       : tag | type | vut_min | vut_max | target_speed | impact% | direction | has_sov
      Vehicle Dimensions : entity | length_m | width_m
      Curve Radii     : vut_speed_max_kmh | direction | radius_m
      Sim Time Bands  : vut_speed_max_kmh | min_s | max_s
    """
    from openpyxl import load_workbook

    wb = load_workbook(path, data_only=True)
    required_sheets = ["Protocol Constants", "Site Settings", "Scenarios",
                       "Vehicle Dimensions", "Curve Radii", "Sim Time Bands"]
    missing = [s for s in required_sheets if s not in wb.sheetnames]
    if missing:
        raise ConfigError(
            f"{path.name} is missing sheet(s): {', '.join(missing)}. "
            f"Regenerate it with: python tools/make_config_xlsx.py"
        )

    raw: dict = {}
    for sheet in ("Protocol Constants", "Site Settings"):
        for row in wb[sheet].iter_rows(min_row=2, values_only=True):
            key = str(row[0]).strip() if row[0] is not None else ""
            if not key:
                continue
            value = row[1]
            if key in _LIST_KEYS:
                raw[key] = [s.strip() for s in str(value or "").split(",") if s.strip()]
            else:
                raw[key] = value

    scenarios: dict = {}
    _truthy = (True, "TRUE", "True", "true", 1)
    for row in wb["Scenarios"].iter_rows(min_row=2, values_only=True):
        if row[0] is None:
            continue
        tag, typ, vmin, vmax, side_impact, has_sov = (list(row) + [None] * 6)[:6]
        entry: dict = {"type": str(typ).strip()}
        if vmin is not None and vmax is not None:
            entry["vut_speed_range_kmh"] = [vmin, vmax]
        if side_impact in _truthy:
            entry["side_impact"] = True
        if has_sov in _truthy:
            entry["has_sov"] = True
        scenarios[str(tag).strip()] = entry
    raw["scenarios"] = scenarios

    dims: dict = {}
    for row in wb["Vehicle Dimensions"].iter_rows(min_row=2, values_only=True):
        if row[0] is not None:
            dims[str(row[0]).strip()] = {"length": row[1], "width": row[2]}
    raw["vehicle_dimensions"] = dims

    raw["curve_part2_radii_m"] = [
        {"vut_speed_max_kmh": r[0], "direction": str(r[1]).strip(), "radius_m": r[2]}
        for r in wb["Curve Radii"].iter_rows(min_row=2, values_only=True)
        if r[0] is not None
    ]
    raw["simulation_time_by_speed_s"] = [
        {"vut_speed_max_kmh": r[0], "min_s": r[1], "max_s": r[2]}
        for r in wb["Sim Time Bands"].iter_rows(min_row=2, values_only=True)
        if r[0] is not None
    ]

    # Prefixes for scenario families that have no row in the Scenarios sheet
    # (scenario-derived prefixes are auto-unioned by Config.load()).
    extra = raw.pop("extra_scenario_prefixes", [])
    raw["naming_convention"] = {"valid_prefixes": list(extra)}
    return raw


class CheckResult(BaseModel):
    check_id: str
    category: str
    description: str
    status: CheckStatus
    comment: str = ""
    source_file: str = ""
    automatable_or_manual: Literal["Automatable", "Manual"] = "Automatable"
    # Intrinsic trust tier (Fully/Partially Automated or Manual) + one-line reason,
    # looked up from the automation registry by check id. See src/automation.py.
    automation_level: str = ""
    automation_note: str = ""
    timestamp: str = Field(default_factory=lambda: datetime.now().strftime("%Y-%m-%d %H:%M:%S"))
    suggested_fix: str = ""

    @model_validator(mode="after")
    def normalize_review_fields(self) -> CheckResult:
        if self.status == "MANUAL_REVIEW":
            self.automatable_or_manual = "Manual"
        if self.status == "FAIL" and not self.suggested_fix:
            self.suggested_fix = self.comment or "Review the failing check and correct the source data."
        if not self.automation_level or not self.automation_note:
            level, note = automation_for(self.check_id)
            self.automation_level = self.automation_level or level
            self.automation_note = self.automation_note or note
        return self

    @property
    def result(self) -> Literal["Yes", "No", "NA", "Manual"]:
        status_map = {"PASS": "Yes", "FAIL": "No", "NA": "NA", "MANUAL_REVIEW": "Manual"}
        return status_map[self.status]  # type: ignore[return-value]

    def as_validation_row(self) -> list[str]:
        """Full row including Comment - for Excel only."""
        return [
            self.check_id,
            self.category,
            self.description,
            self.result,
            self.comment,
            self.source_file,
            self.timestamp,
            self.automation_level,
            self.automation_note,
        ]


class SummaryStats(BaseModel):
    scenario_name: str
    run_timestamp: str
    protocol_version: str
    total: int
    passed: int
    failed: int
    manual: int
    na: int
    pass_rate: float
    critical_failures: list[str]
    scenario_dir: str = ""
    config_path: str = ""
    cli_command: str = ""
    final_status: str = ""
    automatable_total: int = 0
    automatable_passed: int = 0
    automatable_failed: int = 0
    # Reviewer-checklist export layout, carried from config (defaults mirror the reviewer
    # file). The native Validation sheet widths stay hardcoded.
    checklist_column_widths: dict[int, float] = {}

    @classmethod
    def from_results(
        cls,
        results: list[CheckResult],
        scenario_name: str,
        run_timestamp: str,
        protocol_version: str,
        scenario_dir: str = "",
        config_path: str = "",
        cli_command: str = "",
        checklist_column_widths: dict[int, float] | None = None,
    ) -> SummaryStats:
        passed = sum(1 for r in results if r.status == "PASS")
        failed = sum(1 for r in results if r.status == "FAIL")
        manual = sum(1 for r in results if r.status == "MANUAL_REVIEW")
        na = sum(1 for r in results if r.status == "NA")
        total = len(results)
        automatable_results = [
            r for r in results
            if r.automatable_or_manual == "Automatable" and r.status in ("PASS", "FAIL")
        ]
        automatable_passed = sum(1 for r in automatable_results if r.status == "PASS")
        automatable_failed = sum(1 for r in automatable_results if r.status == "FAIL")
        automatable_total = len(automatable_results)
        rate = round((automatable_passed / automatable_total * 100) if automatable_total else 0, 1)
        critical = [r.check_id for r in results if r.status == "FAIL"]
        return cls(
            scenario_name=scenario_name,
            run_timestamp=run_timestamp,
            protocol_version=protocol_version,
            total=total,
            passed=passed,
            failed=failed,
            manual=manual,
            na=na,
            pass_rate=rate,
            critical_failures=critical,
            scenario_dir=scenario_dir,
            config_path=config_path,
            cli_command=cli_command,
            final_status="FAIL" if failed else "PASS",
            automatable_total=automatable_total,
            automatable_passed=automatable_passed,
            automatable_failed=automatable_failed,
            checklist_column_widths=checklist_column_widths or {},
        )


class VehicleDimensions(BaseModel):
    length: float
    width: float


class SimTimeThreshold(BaseModel):
    vut_speed_max_kmh: float
    min_s: float
    max_s: float


class ScenarioProtocol(BaseModel):
    # INTERNAL impact-tolerance routing key, NOT the EuroNCAP Scenario-Type taxonomy
    # (Longitudinal/Turning/Crossing). It only routes the impact check: 'crossing' ->
    # CH_SC_16 (±5%); 'longitudinal'/'head-on' -> CH_SC_17 (±1%). The impact AXIS
    # (width vs length) is the separate side_impact flag, not this field.
    type: Literal["longitudinal", "crossing", "head-on"] = "longitudinal"
    vut_speed_range_kmh: list[float] | None = None
    # Per-instance designed overlap comes from the scenario FILENAME (the Imp token);
    # this is only a fallback used by CH_SC_16/17 when the filename cannot be parsed.
    impact_overlap_pct: float = 50.0
    # Side-impact scenarios (CMCscp, CBTAfs, CBTAns) measure impact across the VUT
    # LENGTH instead of width (EuroNCAP Protocol §1.2.5).
    side_impact: bool = False
    # True when the scenario includes an SOV (overtaken vehicle) that the protocol
    # permits to be "a GVT or a real vehicle" - drives the CH_SC_22 rename hint.
    has_sov: bool = False

    @field_validator("vut_speed_range_kmh")
    @classmethod
    def two_elements(cls, v):
        if v is not None and len(v) != 2:
            raise ValueError("vut_speed_range_kmh must have exactly 2 elements [min, max]")
        return v


class Config(BaseModel):
    protocol_version: str
    lane_width_m: float
    lane_width_tolerance_m: float
    junction_radius_m: float
    junction_radius_tolerance_m: float
    simulation_time_min_s: float
    simulation_time_max_s: float
    impact_tolerance_pct: float
    required_file_extensions: list[str]
    required_standalone_files: list[str] = []
    vut_entity_names: list[str]
    vehicle_dimensions: dict[str, VehicleDimensions]
    naming_convention: dict
    scenarios: dict[str, ScenarioProtocol]
    # Actor naming registry (EuroNCAP standard names for non-VUT entities)
    encap_actor_names: list[str] = []
    # Config-driven entity detection for static/stationary checks
    static_target_name_patterns: list[str] = []
    stationary_target_name_patterns: list[str] = []
    # Speed-dependent simulation time thresholds (overrides flat min/max when VUT speed is known)
    simulation_time_by_speed_s: list[SimTimeThreshold] = []
    # Tighter tolerance for longitudinal impact checks (CH_SC_17)
    longitudinal_impact_tolerance_pct: float = 1.0
    # CH_SC_16/17: reference-point impact-% sensitivity (how far the % swings across the ±0.1 s
    # sync window) above which the estimate is in the §1.2.5.2 corner-first rotation regime, so
    # the verdict uses the rotation-robust overlap-centre metric instead of the single-point
    # reference reading. Turn-across-path geometry sits well above this; head-on / slow VRU well
    # below, so they keep the precise reference-point reading.
    impact_rotation_sensitivity_pct: float = 25.0
    # CH_SC_18: boundary tolerance (km/h) applied to the protocol VUT-speed range ONLY when the
    # speed is taken from the measured trajectory (no filename token), to absorb vertex
    # discretisation noise at a band edge. The exact filename design token is graded with no
    # tolerance.
    speed_range_tolerance_kmh: float = 0.5
    # Radius around estimated junction centre used to detect crossing waypoints (CH_SC_10)
    junction_waypoint_radius_m: float = 20.0
    # Expected GVT/EMT deceleration rate for braking scenarios (CH_MR_02)
    expected_decel_ms2: float = 4.0
    decel_tolerance_ms2: float = 0.1
    # Upper bound for plausible entity speeds; speeds above this (or negative) are
    # flagged as garbage/incorrect by CH_MR_01.
    speed_sanity_max_kmh: float = 300.0
    # Junction detection (CH_RD_03-06, CH_SC_10) is fully file-based - no scenario list.
    # A junction is treated as a real EuroNCAP intersection (turning OR straight crossing)
    # when its incoming roads come from different directions: any two incoming-road headings
    # differing by more than this many degrees. Lane-structure/transition junctions connect
    # parallel roads (spread ~0) and are excluded.
    junction_intersection_min_spread_deg: float = 30.0
    # ---- Geometry tolerances (previously hardcoded in check logic) ----
    # CH_SC_05: how close to east (0 deg) a WorldPosition heading must be before the
    # negative-y = right-lane heuristic is applied.
    east_heading_tolerance_deg: float = 30.0
    # CH_SC_06 / CH_RD_04: how close the VUT/road heading must be to a cardinal axis
    # (0/90/180/270 deg) to count as straight, axis-aligned travel. World direction itself
    # is NOT constrained - RoadRunner authors scenes in any orientation.
    cardinal_heading_tolerance_deg: float = 5.0
    # CH_RD_01: minimum junction side/connecting-lane width (m). Per EuroNCAP Frontal v1.1
    # Figure 4.2 the main approach lanes are lane_width_m (3.5 m) but the junction side lanes may
    # be 3.25-3.5 m, so connecting-road lanes are graded against [junction_lane_width_min_m,
    # lane_width_m] while main-road lanes stay at lane_width_m exactly.
    junction_lane_width_min_m: float = 3.25
    # CH_SC_05: lateral offset (m) from road centre beyond which the lane side is decided.
    right_lane_offset_threshold_m: float = 0.1
    # CH_RD_04: how close the leftmost junction road's start must be to the RoadRunner
    # origin (0,0) to PASS. Tight by default - the checklist requires (0,0,0) exactly.
    road_origin_tolerance_m: float = 0.01
    # CH_SC_14 obstruction layout (Frontal v1.1 TEST PROCEDURE 3.2.3): the group of parked
    # obstruction vehicles sits 1 m apart bumper-to-bumper, at a lateral offset of 2 m
    # (nearside target approach) or 5.5 m (farside) from the parked-vehicle edge to the VUT
    # trajectory. Used to report the measured obstruction layout against the protocol.
    obstruction_gap_m: float = 1.0
    obstruction_offset_nearside_m: float = 2.0
    obstruction_offset_farside_m: float = 5.5
    obstruction_layout_tolerance_m: float = 1.0
    # get_polyline_curvature_radii / CH_SC_07: minimum per-vertex heading change (rad) and
    # segment length (m) for a polyline section to count as "curving" rather than straight.
    curvature_min_heading_delta_rad: float = 0.01
    curvature_min_segment_length_m: float = 0.01
    # CH_SC_07: protocol Part 2 (constant radius arc) values for CPTA/CCFtap/CMFtap/CBTA.
    # Source: EuroNCAP Frontal Collisions v1.1 Table 1.2.4. Each entry: {vut_speed_max_kmh, direction, radius_m}.
    # Direction "Nearside" = right turn (heading decreases); "Farside" = left turn (heading increases).
    curve_part2_radii_m: list[dict] = []
    # Allowed deviation from the protocol Part 2 radius before a FAIL is issued (%).
    curve_radius_tolerance_pct: float = 20.0
    # Traffic handedness used for far-side / near-side classification (CH_SC_07, CH_SC_20).
    # "LHT" = drive on left (UK/Japan/India - EuroNCAP default per Frontal v1.1 + ISO 8855).
    # "RHT" = drive on right (US/mainland Europe) - inverts Farside/Nearside assignment.
    traffic_handedness: str = "LHT"
    # Optional files reported by NM_03 - absent files do NOT cause FAIL.
    optional_standalone_files: list[str] = []
    # Column widths for the reviewer-checklist export (--checklist) ChecklistFinal sheet,
    # keyed by 1-based column number as a string. The defaults mirror the reviewer file so
    # the export is an exact replica; override a column here only to deviate. Columns:
    # 2 Category, 3 CheckPoint Number, 4 Check Points, 5 Self Review, 6 Review1, 7 Review2,
    # 8 (Issues Log R2 Comment). Any column omitted falls back to the built-in default.
    checklist_column_widths: dict[str, float] = Field(default_factory=lambda: {
        "2": 12.140625, "3": 18.7109375, "4": 196.7109375, "5": 12.7109375,
        "6": 11.85546875, "7": 11.85546875, "8": 13.0,
    })
    # Entity names exempt from the CH_SC_22 NCAP-folder rule. Per checklist Prerequisites,
    # the SOV (vehicle overtaken by VUT in CCFhol) "can either be a GVT or a real vehicle",
    # so a non-NCAP asset path is protocol-legal for it.
    sov_entity_names: list[str] = ["SOV"]
    # ---- Scenario filename grammar (CH_NM_04) ----
    # The team names every scenario base as:
    #   <program>_<type>_<n>VUT_<n><TargetType>_<n>Imp   e.g. AEB_CCFtap_10VUT_30GVT_50Imp
    # These knobs let NM_04 validate that structure (and cross-check the values) without
    # any code edit when the convention grows.
    allowed_programs: list[str] = ["AEB"]
    target_type_tokens: list[str] = []          # GVT / EPTa / EPTc / EBTa / EMT / ...
    # Acceptable OpenSCENARIO entity categories for each filename target token - lets
    # CH_NM_04 catch a mislabeled filename (e.g. "30GVT" on a pedestrian-category target)
    # WITHOUT false-flagging RoadRunner's export reality: it has no cyclist/motorcyclist
    # OSC category, so EBTa/EMT legitimately export as <Vehicle>. Each token therefore maps
    # to the SET of categories that are protocol-correct for it (overlap = no mismatch).
    target_type_to_category: dict[str, set[str]] = Field(default_factory=lambda: {
        "GVT": {"Vehicle"}, "SOV": {"Vehicle"},
        "EPTa": {"Pedestrian"}, "EPTc": {"Pedestrian"},
        "EBTa": {"Bicyclist", "Vehicle"}, "EMT": {"Motorcyclist", "Vehicle"},
    })
    vut_speed_suffix: str = "VUT"
    impact_suffix: str = "Imp"
    # Impact-overlap is a protocol *variant* parameter (10/25/50/75/90 ...). NM_04 checks the
    # filename token is one of these; exact-overlap correctness stays with CH_SC_16/17.
    allowed_impact_overlaps: list[float] = [0, 10, 25, 50, 75, 90, 100]
    # ---- Associated / affix files (CH_NM_03, CH_FB_01) ----
    # Files that ship beside the 7 base-named files, named with a fixed affix around {base}.
    functional_file_pattern: str = "ENCAP_Scenario_func_{base}.xlsm"
    macro_file_pattern: str = "MACRO_{base}.xlsx"
    review_file_pattern: str = "{base}_Review.xlsx"
    # Which associated-file roles are mandatory (the rest are reported but never FAIL).
    required_associated_roles: list[str] = ["functional", "macro"]

    @classmethod
    def load(cls, path: Path | None = None) -> Config:
        config_path = path or Path(__file__).parent.parent / "config.json"

        if config_path.suffix.lower() == ".xlsx":
            raw = _read_excel_config(config_path)
        else:
            try:
                raw = json.loads(config_path.read_text())
            except json.JSONDecodeError as exc:
                raise ConfigError(
                    f"{config_path.name} is not valid JSON - line {exc.lineno}, "
                    f"column {exc.colno}: {exc.msg}. Common causes: a comma after the "
                    f"last item in a list/section, a missing comma between items, or a "
                    f"missing quote. Tip: run 'python validator.py <dir> --check-config' "
                    f"after editing, or use config.xlsx instead (see CONFIG_GUIDE.md)."
                ) from exc

        # strip any top-level documentation keys (any key starting with "_"),
        # so config.json can carry inline guidance/comments for editors.
        for key in [k for k in raw if k.startswith("_")]:
            raw.pop(key)
        for section in ("vehicle_dimensions", "scenarios"):
            if section not in raw:
                raise ConfigError(
                    f"{config_path.name} is missing the required '{section}' section. "
                    f"See CONFIG_GUIDE.md for what belongs there."
                )
        try:
            # coerce nested dicts
            raw["vehicle_dimensions"] = {
                k: VehicleDimensions(**v) for k, v in raw["vehicle_dimensions"].items()
            }
            raw["scenarios"] = {
                k: ScenarioProtocol(**v)
                for k, v in raw["scenarios"].items()
                if not k.startswith("_")
            }
            raw["simulation_time_by_speed_s"] = [
                SimTimeThreshold(**t) for t in raw.get("simulation_time_by_speed_s", [])
            ]
            cfg = cls(**raw)
        except ValidationError as exc:
            problems = []
            for err in exc.errors():
                loc = ".".join(str(p) for p in err.get("loc", ())) or "(top level)"
                problems.append(f"  - '{loc}': {err.get('msg', 'invalid value')}")
            raise ConfigError(
                f"{config_path.name} has {len(problems)} invalid or missing value(s):\n"
                + "\n".join(problems)
                + "\n  Fix the value(s) listed above - see CONFIG_GUIDE.md for each key."
            ) from exc
        # One-place editing: adding a scenario under "scenarios" auto-registers its
        # tag for detection - no need to also edit naming_convention.valid_prefixes.
        # The scenario key's prefix (text before any "-") is unioned into valid_prefixes.
        prefixes = list(cfg.naming_convention.get("valid_prefixes", []))
        for key in cfg.scenarios:
            prefix = key.split("-")[0]
            if prefix and prefix not in prefixes:
                prefixes.append(prefix)
        cfg.naming_convention["valid_prefixes"] = prefixes
        return cfg

    def scenario_protocol(self, scenario_tag: str) -> ScenarioProtocol | None:
        # Longest-key-first so a specific sub-variant entry (e.g. CBTAns, which carries
        # side_impact=True) wins over its generic family prefix (CBTA), instead of whichever
        # happens to be earlier in insertion order. Mirrors detect_scenario_tag's longest-prefix
        # rule so the routing key AND the side-impact axis come from the most specific match.
        tag_upper = scenario_tag.upper()
        for key in sorted(self.scenarios, key=len, reverse=True):
            if tag_upper.startswith(key.upper()):
                return self.scenarios[key]
        return None

    def vut_dims(self) -> VehicleDimensions:
        return self.vehicle_dimensions.get("VUT", self.vehicle_dimensions["default_car"])

    def target_dims(self, entity_name: str = "GVT") -> VehicleDimensions:
        for key in self.vehicle_dimensions:
            if key.lower() in entity_name.lower():
                return self.vehicle_dimensions[key]
        return self.vehicle_dimensions["default_car"]

    def associated_files(self, base: str) -> list[tuple[str, str, str, bool]]:
        """Resolve the affix files for a scenario base name.

        Returns (role, expected_name, glob, required) per role. `expected_name`
        has {base} substituted; `glob` substitutes `*` so the file can be
        auto-detected even when the base segment drifts or the config is stale
        (so a misnamed-but-present file is found, not short-circuited to missing).
        """
        patterns = [
            ("functional", self.functional_file_pattern),
            ("macro", self.macro_file_pattern),
            ("review", self.review_file_pattern),
        ]
        return [
            (role, pattern.format(base=base), pattern.replace("{base}", "*"),
             role in self.required_associated_roles)
            for role, pattern in patterns
            if pattern
        ]

    def functional_file_name(self, base: str) -> str:
        """Resolved name of the functional / Test-Automation workbook for CH_FB_01."""
        return self.functional_file_pattern.format(base=base)
