from __future__ import annotations

import json
from datetime import datetime
from pathlib import Path
from typing import Literal

from pydantic import BaseModel, Field, ValidationError, field_validator, model_validator


class ConfigError(Exception):
    """Configuration problem with a user-facing, plain-language message.

    Raised by Config.load() instead of letting json/pydantic stack traces reach
    non-developer users. validator.py prints str(exc) without a traceback.
    """


# Config keys whose Excel cell holds a comma-separated list.
_LIST_KEYS = {
    "vut_entity_names", "encap_actor_names", "sov_entity_names",
    "static_target_name_patterns", "stationary_target_name_patterns",
    "required_file_extensions", "required_standalone_files",
    "optional_standalone_files", "junction_scenario_prefixes",
    "extra_scenario_prefixes",
    "allowed_programs", "target_type_tokens", "required_associated_roles",
    "allowed_impact_overlaps",
}


def _read_excel_config(path: Path) -> dict:
    """Read config.xlsx (generated by tools/make_config_xlsx.py) into the same raw
    dict shape that json.loads(config.json) produces. Sheets:
      Protocol Constants / Site Settings : key | value | description rows
      Scenarios       : tag | type | vut_min | vut_max | target_speed | impact% | direction | has_sov
      Vehicle Dimensions : entity | length_m | width_m
      Curve Radii     : vut_speed_max_kmh | direction | radius_m
      Sim Time Bands  : vut_speed_max_kmh | min_s | max_s
    """
    from openpyxl import load_workbook

    wb = load_workbook(path, data_only=True)
    required_sheets = ["Protocol Constants", "Site Settings", "Scenarios",
                       "Vehicle Dimensions", "Curve Radii", "Sim Time Bands"]
    missing = [s for s in required_sheets if s not in wb.sheetnames]
    if missing:
        raise ConfigError(
            f"{path.name} is missing sheet(s): {', '.join(missing)}. "
            f"Regenerate it with: python tools/make_config_xlsx.py"
        )

    raw: dict = {}
    for sheet in ("Protocol Constants", "Site Settings"):
        for row in wb[sheet].iter_rows(min_row=2, values_only=True):
            key = str(row[0]).strip() if row[0] is not None else ""
            if not key:
                continue
            value = row[1]
            if key in _LIST_KEYS:
                raw[key] = [s.strip() for s in str(value or "").split(",") if s.strip()]
            else:
                raw[key] = value

    scenarios: dict = {}
    for row in wb["Scenarios"].iter_rows(min_row=2, values_only=True):
        if row[0] is None:
            continue
        tag, typ, vmin, vmax, tspeed, imp, direction, has_sov = (list(row) + [None] * 8)[:8]
        entry: dict = {"type": str(typ).strip(), "direction": str(direction or "").strip()}
        if imp is not None:
            entry["impact_overlap_pct"] = imp
        if vmin is not None and vmax is not None:
            entry["vut_speed_range_kmh"] = [vmin, vmax]
        if tspeed is not None:
            entry["target_speed_kmh"] = tspeed
        if has_sov in (True, "TRUE", "True", "true", 1):
            entry["has_sov"] = True
        scenarios[str(tag).strip()] = entry
    raw["scenarios"] = scenarios

    dims: dict = {}
    for row in wb["Vehicle Dimensions"].iter_rows(min_row=2, values_only=True):
        if row[0] is not None:
            dims[str(row[0]).strip()] = {"length": row[1], "width": row[2]}
    raw["vehicle_dimensions"] = dims

    raw["curve_part2_radii_m"] = [
        {"vut_speed_max_kmh": r[0], "direction": str(r[1]).strip(), "radius_m": r[2]}
        for r in wb["Curve Radii"].iter_rows(min_row=2, values_only=True)
        if r[0] is not None
    ]
    raw["simulation_time_by_speed_s"] = [
        {"vut_speed_max_kmh": r[0], "min_s": r[1], "max_s": r[2]}
        for r in wb["Sim Time Bands"].iter_rows(min_row=2, values_only=True)
        if r[0] is not None
    ]

    # Prefixes for scenario families that have no row in the Scenarios sheet
    # (scenario-derived prefixes are auto-unioned by Config.load()).
    extra = raw.pop("extra_scenario_prefixes", [])
    raw["naming_convention"] = {"valid_prefixes": list(extra)}
    return raw


class CheckResult(BaseModel):
    check_id: str
    category: str
    description: str
    status: Literal["PASS", "FAIL", "NA", "MANUAL_REVIEW"]
    comment: str = ""
    source_file: str = ""
    severity: str = "Medium"
    automatable_or_manual: Literal["Automatable", "Manual"] = "Automatable"
    timestamp: str = Field(default_factory=lambda: datetime.now().strftime("%Y-%m-%d %H:%M:%S"))
    suggested_fix: str = ""

    @model_validator(mode="after")
    def normalize_review_fields(self) -> CheckResult:
        if self.status == "MANUAL_REVIEW":
            self.automatable_or_manual = "Manual"
            if not self.severity:
                self.severity = "Low"
        elif not self.severity:
            self.severity = "High" if self.status == "FAIL" else "Medium"
        if self.status == "FAIL" and not self.suggested_fix:
            self.suggested_fix = self.comment or "Review the failing check and correct the source data."
        return self

    @property
    def result(self) -> Literal["Yes", "No", "NA", "Manual"]:
        status_map = {"PASS": "Yes", "FAIL": "No", "NA": "NA", "MANUAL_REVIEW": "Manual"}
        return status_map[self.status]  # type: ignore[return-value]

    def as_validation_row(self) -> list[str]:
        """Full row including Comment — for Excel only."""
        return [
            self.check_id,
            self.category,
            self.description,
            self.result,
            self.comment,
            self.source_file,
            self.severity,
            self.automatable_or_manual,
            self.timestamp,
        ]

    def as_csv_row(self) -> list[str]:
        """Row WITHOUT Comment — for CSV export (Comment is proprietary)."""
        return [
            self.check_id,
            self.category,
            self.description,
            self.result,
            self.source_file,
            self.severity,
            self.automatable_or_manual,
            self.timestamp,
        ]


class SummaryStats(BaseModel):
    scenario_name: str
    run_timestamp: str
    protocol_version: str
    total: int
    passed: int
    failed: int
    manual: int
    na: int
    pass_rate: float
    critical_failures: list[str]
    scenario_dir: str = ""
    config_path: str = ""
    template_path: str = ""
    cli_command: str = ""
    final_status: str = ""
    automatable_total: int = 0
    automatable_passed: int = 0
    automatable_failed: int = 0

    @classmethod
    def from_results(
        cls,
        results: list[CheckResult],
        scenario_name: str,
        run_timestamp: str,
        protocol_version: str,
        scenario_dir: str = "",
        config_path: str = "",
        template_path: str = "",
        cli_command: str = "",
    ) -> SummaryStats:
        passed = sum(1 for r in results if r.status == "PASS")
        failed = sum(1 for r in results if r.status == "FAIL")
        manual = sum(1 for r in results if r.status == "MANUAL_REVIEW")
        na = sum(1 for r in results if r.status == "NA")
        total = len(results)
        automatable_results = [
            r for r in results
            if r.automatable_or_manual == "Automatable" and r.status in ("PASS", "FAIL")
        ]
        automatable_passed = sum(1 for r in automatable_results if r.status == "PASS")
        automatable_failed = sum(1 for r in automatable_results if r.status == "FAIL")
        automatable_total = len(automatable_results)
        rate = round((automatable_passed / automatable_total * 100) if automatable_total else 0, 1)
        critical = [r.check_id for r in results if r.status == "FAIL"]
        return cls(
            scenario_name=scenario_name,
            run_timestamp=run_timestamp,
            protocol_version=protocol_version,
            total=total,
            passed=passed,
            failed=failed,
            manual=manual,
            na=na,
            pass_rate=rate,
            critical_failures=critical,
            scenario_dir=scenario_dir,
            config_path=config_path,
            template_path=template_path,
            cli_command=cli_command,
            final_status="FAIL" if failed else "PASS",
            automatable_total=automatable_total,
            automatable_passed=automatable_passed,
            automatable_failed=automatable_failed,
        )


class VehicleDimensions(BaseModel):
    length: float
    width: float


class SimTimeThreshold(BaseModel):
    vut_speed_max_kmh: float
    min_s: float
    max_s: float


class ScenarioProtocol(BaseModel):
    type: Literal["longitudinal", "crossing", "head-on"] = "longitudinal"
    vut_speed_range_kmh: list[float] | None = None
    target_speed_kmh: float | None = None
    impact_overlap_pct: float = 50.0
    direction: str = "left-to-right"
    # True when the scenario includes an SOV (overtaken vehicle) that the protocol
    # permits to be "a GVT or a real vehicle" — drives the CH_SC_22 rename hint.
    has_sov: bool = False

    @field_validator("vut_speed_range_kmh")
    @classmethod
    def two_elements(cls, v):
        if v is not None and len(v) != 2:
            raise ValueError("vut_speed_range_kmh must have exactly 2 elements [min, max]")
        return v


class Config(BaseModel):
    protocol_version: str
    lane_width_m: float
    lane_width_tolerance_m: float
    junction_radius_m: float
    junction_radius_tolerance_m: float
    simulation_time_min_s: float
    simulation_time_max_s: float
    impact_tolerance_pct: float
    required_file_extensions: list[str]
    required_standalone_files: list[str] = []
    vut_entity_names: list[str]
    vehicle_dimensions: dict[str, VehicleDimensions]
    naming_convention: dict
    scenarios: dict[str, ScenarioProtocol]
    # Actor naming registry (EuroNCAP standard names for non-VUT entities)
    encap_actor_names: list[str] = []
    # Config-driven entity detection for static/stationary checks
    static_target_name_patterns: list[str] = []
    stationary_target_name_patterns: list[str] = []
    # Speed-dependent simulation time thresholds (overrides flat min/max when VUT speed is known)
    simulation_time_by_speed_s: list[SimTimeThreshold] = []
    # Tighter tolerance for longitudinal impact checks (CH_SC_17)
    longitudinal_impact_tolerance_pct: float = 1.0
    # Radius around estimated junction centre used to detect crossing waypoints (CH_SC_10)
    junction_waypoint_radius_m: float = 20.0
    # Expected GVT/EMT deceleration rate for braking scenarios (CH_MR_02)
    expected_decel_ms2: float = 4.0
    decel_tolerance_ms2: float = 0.1
    # Upper bound for plausible entity speeds; speeds above this (or negative) are
    # flagged as garbage/incorrect by CH_MR_01.
    speed_sanity_max_kmh: float = 300.0
    # Scenario name prefixes that require EuroNCAP junction geometry (CH_RD_03/04/05/06).
    # Curved-following scenarios (CCF*) have junction elements in their xodr for lane
    # structure, not intersections - those checks must be skipped for them.
    junction_scenario_prefixes: list[str] = []
    # File-heuristic fallback for junction detection (CH_RD_03-06, CH_SC_10): if the .xodr
    # contains a junction whose connecting roads turn through a radius at or below this value,
    # the junction geometry checks run EVEN IF the scenario tag is not in
    # junction_scenario_prefixes. This stops an un-configured turn/crossing scenario from
    # silently short-circuiting to NA (the CCFtap class of bug). Lane-structure/transition
    # junctions have no tight arcs and stay excluded.
    junction_detect_max_radius_m: float = 50.0
    # ---- Geometry tolerances (previously hardcoded in check logic) ----
    # CH_SC_05: how close to east (0 deg) a WorldPosition heading must be before the
    # negative-y = right-lane heuristic is applied.
    east_heading_tolerance_deg: float = 30.0
    # CH_SC_06 / CH_RD_04: how close the VUT/road heading must be to a cardinal axis
    # (0/90/180/270 deg) to count as straight, axis-aligned travel. World direction itself
    # is NOT constrained - RoadRunner authors scenes in any orientation.
    cardinal_heading_tolerance_deg: float = 5.0
    # CH_SC_05: lateral offset (m) from road centre beyond which the lane side is decided.
    right_lane_offset_threshold_m: float = 0.1
    # get_polyline_curvature_radii / CH_SC_07: minimum per-vertex heading change (rad) and
    # segment length (m) for a polyline section to count as "curving" rather than straight.
    curvature_min_heading_delta_rad: float = 0.01
    curvature_min_segment_length_m: float = 0.01
    # CH_SC_07: protocol Part 2 (constant radius arc) values for CPTA/CCFtap/CMFtap/CBTA.
    # Source: EuroNCAP Frontal Collisions v1.1 Table 1.2.4. Each entry: {vut_speed_max_kmh, direction, radius_m}.
    # Direction "Nearside" = right turn (heading decreases); "Farside" = left turn (heading increases).
    curve_part2_radii_m: list[dict] = []
    # Allowed deviation from the protocol Part 2 radius before a FAIL is issued (%).
    curve_radius_tolerance_pct: float = 20.0
    # Traffic handedness used for far-side / near-side classification (CH_SC_07, CH_SC_20).
    # "LHT" = drive on left (UK/Japan/India — EuroNCAP default per Frontal v1.1 + ISO 8855).
    # "RHT" = drive on right (US/mainland Europe) — inverts Farside/Nearside assignment.
    traffic_handedness: str = "LHT"
    # Optional files reported by NM_03 — absent files do NOT cause FAIL.
    optional_standalone_files: list[str] = []
    # Entity names exempt from the CH_SC_22 NCAP-folder rule. Per checklist Prerequisites,
    # the SOV (vehicle overtaken by VUT in CCFhol) "can either be a GVT or a real vehicle",
    # so a non-NCAP asset path is protocol-legal for it.
    sov_entity_names: list[str] = ["SOV"]
    # ---- Scenario filename grammar (CH_NM_02) ----
    # The team names every scenario base as:
    #   <program>_<type>_<n>VUT_<n><TargetType>_<n>Imp   e.g. AEB_CCFtap_10VUT_30GVT_50Imp
    # These knobs let NM_02 validate that structure (and cross-check the values) without
    # any code edit when the convention grows.
    allowed_programs: list[str] = ["AEB"]
    target_type_tokens: list[str] = []          # GVT / EPTa / EPTc / EBTa / EMT / ...
    vut_speed_suffix: str = "VUT"
    impact_suffix: str = "Imp"
    # Impact-overlap is a protocol *variant* parameter (10/25/50/75/90 ...). NM_02 checks the
    # filename token is one of these; exact-overlap correctness stays with CH_SC_16/17.
    allowed_impact_overlaps: list[float] = [0, 10, 25, 50, 75, 90, 100]
    # ---- Associated / affix files (CH_NM_03, CH_FB_01) ----
    # Files that ship beside the 7 base-named files, named with a fixed affix around {base}.
    functional_file_pattern: str = "ENCAP_Scenario_func_{base}.xlsm"
    macro_file_pattern: str = "MACRO_{base}.xlsx"
    review_file_pattern: str = "{base}_Review.xlsx"
    # Which associated-file roles are mandatory (the rest are reported but never FAIL).
    required_associated_roles: list[str] = ["functional", "macro"]

    @classmethod
    def load(cls, path: Path | None = None) -> Config:
        config_path = path or Path(__file__).parent.parent / "config.json"

        if config_path.suffix.lower() == ".xlsx":
            raw = _read_excel_config(config_path)
        else:
            try:
                raw = json.loads(config_path.read_text())
            except json.JSONDecodeError as exc:
                raise ConfigError(
                    f"{config_path.name} is not valid JSON — line {exc.lineno}, "
                    f"column {exc.colno}: {exc.msg}. Common causes: a comma after the "
                    f"last item in a list/section, a missing comma between items, or a "
                    f"missing quote. Tip: run 'python validator.py <dir> --check-config' "
                    f"after editing, or use config.xlsx instead (see CONFIG_GUIDE.md)."
                ) from exc

        # strip any top-level documentation keys (any key starting with "_"),
        # so config.json can carry inline guidance/comments for editors.
        for key in [k for k in raw if k.startswith("_")]:
            raw.pop(key)
        for section in ("vehicle_dimensions", "scenarios"):
            if section not in raw:
                raise ConfigError(
                    f"{config_path.name} is missing the required '{section}' section. "
                    f"See CONFIG_GUIDE.md for what belongs there."
                )
        try:
            # coerce nested dicts
            raw["vehicle_dimensions"] = {
                k: VehicleDimensions(**v) for k, v in raw["vehicle_dimensions"].items()
            }
            raw["scenarios"] = {
                k: ScenarioProtocol(**v)
                for k, v in raw["scenarios"].items()
                if not k.startswith("_")
            }
            raw["simulation_time_by_speed_s"] = [
                SimTimeThreshold(**t) for t in raw.get("simulation_time_by_speed_s", [])
            ]
            cfg = cls(**raw)
        except ValidationError as exc:
            problems = []
            for err in exc.errors():
                loc = ".".join(str(p) for p in err.get("loc", ())) or "(top level)"
                problems.append(f"  - '{loc}': {err.get('msg', 'invalid value')}")
            raise ConfigError(
                f"{config_path.name} has {len(problems)} invalid or missing value(s):\n"
                + "\n".join(problems)
                + "\n  Fix the value(s) listed above — see CONFIG_GUIDE.md for each key."
            ) from exc
        # One-place editing: adding a scenario under "scenarios" auto-registers its
        # tag for detection - no need to also edit naming_convention.valid_prefixes.
        # The scenario key's prefix (text before any "-") is unioned into valid_prefixes.
        prefixes = list(cfg.naming_convention.get("valid_prefixes", []))
        for key in cfg.scenarios:
            prefix = key.split("-")[0]
            if prefix and prefix not in prefixes:
                prefixes.append(prefix)
        cfg.naming_convention["valid_prefixes"] = prefixes
        return cfg

    def scenario_protocol(self, scenario_tag: str) -> ScenarioProtocol | None:
        for key, proto in self.scenarios.items():
            if scenario_tag.upper().startswith(key.upper()):
                return proto
        return None

    def vut_dims(self) -> VehicleDimensions:
        return self.vehicle_dimensions.get("VUT", self.vehicle_dimensions["default_car"])

    def target_dims(self, entity_name: str = "GVT") -> VehicleDimensions:
        for key in self.vehicle_dimensions:
            if key.lower() in entity_name.lower():
                return self.vehicle_dimensions[key]
        return self.vehicle_dimensions["default_car"]

    def associated_files(self, base: str) -> list[tuple[str, str, str, bool]]:
        """Resolve the affix files for a scenario base name.

        Returns (role, expected_name, glob, required) per role. `expected_name`
        has {base} substituted; `glob` substitutes `*` so the file can be
        auto-detected even when the base segment drifts or the config is stale
        (so a misnamed-but-present file is found, not short-circuited to missing).
        """
        patterns = [
            ("functional", self.functional_file_pattern),
            ("macro", self.macro_file_pattern),
            ("review", self.review_file_pattern),
        ]
        return [
            (role, pattern.format(base=base), pattern.replace("{base}", "*"),
             role in self.required_associated_roles)
            for role, pattern in patterns
            if pattern
        ]

    def functional_file_name(self, base: str) -> str:
        """Resolved name of the functional / Test-Automation workbook for CH_FB_01."""
        return self.functional_file_pattern.format(base=base)
